// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsServiceApi.Model;

#nullable disable

namespace StudentsServiceApi.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20250214092953_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentsServiceApi.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "address1",
                            DateOfBirth = new DateTime(2025, 2, 14, 9, 29, 53, 62, DateTimeKind.Utc).AddTicks(6733),
                            Email = "email1@mail.com",
                            Name = "John",
                            PhoneNumber = "012345689"
                        },
                        new
                        {
                            Id = 2,
                            Address = "address2",
                            DateOfBirth = new DateTime(2025, 2, 14, 9, 29, 53, 62, DateTimeKind.Utc).AddTicks(6963),
                            Email = "email2@mail.com",
                            Name = "Alice",
                            PhoneNumber = "123456890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
